### ISSUE TITLE
Push version 3 to dockerhub

### ISSUE THREAD

**Issue by roonie007** [linkyard/docker-helm#25]
Can you please push the latest version 3.0.1 to the dockerhub ?

**Comment by woodcockjosh** [comment]
Any update on this???

**Comment by msiegenthaler** [comment]
Hey, sorry for missing this request. We have switched to using https://hub.docker.com/r/alpine/helm for the 3.0 version of helm internally and only keep this repo for 2.x. Is there anything that keeps you from using the alpine:helm?

**Comment by woodcockjosh** [comment]
You should probably put a deprecation notice on the readme of master branch

**Comment by msiegenthaler** [comment]
That makes sense! I've done so
