### ISSUE TITLE
Push version 2.15.2 to  Docker Hub

### ISSUE THREAD

**Issue by kir4h** [linkyard/docker-helm#26]
Hi @msiegenthaler ,

Just realized there is a `2.15.2` version but doesn't seem to be pushed to Docker Hub (latest one is `2.14.1`. Could you please push it? 

Thanks for your work!

**Comment by msiegenthaler** [comment]
Sure, I've just pushed it

**Comment by kir4h** [comment]
Thanks a lot! There is a newer version for the `2.xx` release, `2.16.8`. Maybe we can create a `2.xx` branch out of the `2.15.2` commit and then bump it to `2.16.8`  (did https://github.com/kir4h/docker-helm/commit/cc9160768f968b5e60d89c41020654a3df8bee28 yesterday to have a temporary solution, but if we create the branch I can create a PR to it or you can just bump it yourself if you have spare time).
